license_id: cc-by
methodology: Other
methodology_other: https://gdacs.org/Knowledge/overview.aspx
caveats: While we try everything to ensure accuracy, this information is purely indicative and should not be used for any decision making without alternate sources of information. The JRC is not responsible for any damage or loss resulting from use of the information presented on this website.
dataset_source: European Union
package_creator: HDX Data Systems Team
private: False
maintainer: aa13de36-28c5-47a7-8d0b-6d7c754ba8c8
owner_org:  f27b8618-52b9-4827-9440-eb65a1f66d41
data_update_frequency: 1
notes: GDACS alerts are issued for earthquakes and possible subsequent tsunamis, tropical cyclones, floods and volcanoes. Earthquake, tsunami and tropical cyclones calculations and assessments are done automatically, without human intervention. Floods and volcanic eruptions are currently manually introduced. Research and development is continuous to improve the global monitoring.
subnational: "1"
