# Collector specific configuration

base_url: "https://www.gdacs.org/XML/RSS.xml"

dataset_name: "gdacs-rss-information"

dataset_title: "GDACS RSS Information"

disaster_conversion:
  "DR": "Drought"
  "EQ": "Earthquake"
  "FL": "Flood"
  "TC": "Tropical Cyclone"
  "VO": "Volcano"
  "WF": "Wildfire"

tags:
  - "cyclones-hurricanes-typhoons"
  - "earthquake-tsunami"
  - "flooding"
  - "natural disasters"
